## -*- encoding: utf-8 -*-
## This file (understandingFunctionsSoln.draft.sagetex.sage) was *autogenerated* from understandingFunctionsSoln.draft.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('understandingFunctionsSoln.draft', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
