## -*- encoding: utf-8 -*-
## This file (understandingFunctionsSoln.sagetex.sage) was *autogenerated* from understandingFunctionsSoln.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('understandingFunctionsSoln', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
