## -*- encoding: utf-8 -*-
## This file (understandingFunctions.sagetex.sage) was *autogenerated* from understandingFunctions.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('understandingFunctions', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
