## -*- encoding: utf-8 -*-
## This file (understandingFunctions.sagetex.sage) was *autogenerated* from understandingFunctions.tex with sagetex.sty version 2022/08/21 v3.6.1.
import sagetex
_st_ = sagetex.SageTeXProcessor('understandingFunctions', version='2022/08/21 v3.6.1', version_check=True)
_st_.endofdoc()
