## -*- encoding: utf-8 -*-
## This file (approximatingTheAreaUnderACurveSoln.sagetex.sage) was *autogenerated* from approximatingTheAreaUnderACurveSoln.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('approximatingTheAreaUnderACurveSoln', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
