## -*- encoding: utf-8 -*-
## This file (q4_xm.sagetex.sage) was *autogenerated* from q4_xm.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('q4_xm', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
