## -*- encoding: utf-8 -*-
## This file (indeterminateForms.sagetex.sage) was *autogenerated* from indeterminateForms.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('indeterminateForms', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
