## -*- encoding: utf-8 -*-
## This file (q7_soln.sagetex.sage) was *autogenerated* from q7_soln.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('q7_soln', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
