## -*- encoding: utf-8 -*-
## This file (FTCSoln.online.sagetex.sage) was *autogenerated* from FTCSoln.online.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('FTCSoln.online', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
