## -*- encoding: utf-8 -*-
## This file (continuityAndIVT.online.sagetex.sage) was *autogenerated* from continuityAndIVT.online.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('continuityAndIVT.online', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
