## -*- encoding: utf-8 -*-
## This file (substitutionSoln.online.sagetex.sage) was *autogenerated* from substitutionSoln.online.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('substitutionSoln.online', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
