## -*- encoding: utf-8 -*-
## This file (maximumsAndMinimums.online.sagetex.sage) was *autogenerated* from maximumsAndMinimums.online.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('maximumsAndMinimums.online', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
