## -*- encoding: utf-8 -*-
## This file (q5_soln.online.sagetex.sage) was *autogenerated* from q5_soln.online.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('q5_soln.online', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
