## -*- encoding: utf-8 -*-
## This file (summary.online.sagetex.sage) was *autogenerated* from summary.online.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('summary.online', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
