## -*- encoding: utf-8 -*-
## This file (optimizationSoln.sagetex.sage) was *autogenerated* from optimizationSoln.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('optimizationSoln', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
