## -*- encoding: utf-8 -*-
## This file (q2_xm.sagetex.sage) was *autogenerated* from q2_xm.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('q2_xm', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
