## -*- encoding: utf-8 -*-
## This file (derivativesAsFunctionsSoln.online.sagetex.sage) was *autogenerated* from derivativesAsFunctionsSoln.online.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('derivativesAsFunctionsSoln.online', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
