## -*- encoding: utf-8 -*-
## This file (lHopitalsRuleSoln.online.sagetex.sage) was *autogenerated* from lHopitalsRuleSoln.online.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('lHopitalsRuleSoln.online', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
